#!/bin/bash

WORKSPACE=/var/lib/jenkins/jobs/HRT/workspace
BACKUP_DIR=/home/shared/hrt_backups

source /var/lib/jenkins/.rvm/scripts/rvm
source $WORKSPACE/.rvmrc_ree
$WORKSPACE/db/cron/db_backup.rb resourcetracking $BACKUP_DIR >> $BACKUP_DIR/cron.log